{% set version = "0.2-23" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeltools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeltools/modeltools_{{ version }}.tar.gz
  sha256: 6b3e8d5af1a039db5c178498dbf354ed1c5627a8cea9229726644053443210ef

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('modeltools')"           # [not win]
    - "\"%R%\" -e \"library('modeltools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=modeltools
  license: GPL-2.0-only
  summary: A collection of tools to deal with statistical models.  The functionality is experimental and the user interface is likely to change in the future. The
    documentation is rather terse, but packages `coin' and `party' have some working examples. However, if you find the implemented ideas interesting we would be
    very interested in a discussion of this proposal. Contributions are more than welcome!
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
