{% set version = '0.2-22' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeltools
  version: {{ version|replace("-", "_") }}

source:
  fn: modeltools_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/modeltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeltools/modeltools_{{ version }}.tar.gz
  sha256: 256a088fc80b0d9182f984f9bd3d6207fb7c1e743f72e2ecb480e6c1d4ac34e9

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('modeltools')"           # [not win]
    - "\"%R%\" -e \"library('modeltools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=modeltools
  license: GPL-2
  summary: A collection of tools to deal with statistical models.  The functionality is experimental
    and the user interface is likely to change in the future. The documentation is rather
    terse, but packages `coin' and `party' have some working examples. However, if you
    find the implemented ideas interesting we would be very interested in a discussion
    of this proposal. Contributions are more than welcome!
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
