appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: g9qaSeRPHtvg2sprjyIdDgoA4ARtSI17zLrXAB5/SbNJ7RgqLK6mzKcIP4xZNS9fTpecKDvfj9tbF7UWZ6rbm7Vi7qabV4Ud4xSLJaKzDtwRwroo9/x44raSs6qDf29VrziWmWBye3ofIGx+VeG0r8W+1O44TpSeBiipB5J26HevpI9oRJ4b9VelWBpqX/IdoMxA6b5hqZGM1TR9WXud1iw1LCfltbnym5ifthcOG/pMSNymPXiXy/UyDzJkOmmWm/MY+1ll9wiGe9xEmeO5a24ZzpoSlk1q/0JZfU5NFds+HHjCVwVsPxxa8CWuq59/d+F2DERwVn7m+zeiuS1cel3L2EUOS1vL+eoyjl9tJxl8NPafJv39jgBZ2x7eCz9m5Q29E1WJDSeX61MuBeDA+PNWsNXOi86Q3cQ403vHRrPpmJ2vkxbmAEL8Wus+jkm4LJ9D0f1kMQyAKojVBz2cx9OAf/B3mNW9OgSSRf7v3/3hjiE4GvbDiWGuJ/vGfjzZsCh8DkSyL3z/KLZTufIOTIyGIVAfUc/UPjpQBOdBogfPhxhplbvgcxhmHNhAad2zevqQWmnjoCYnem2aDUOj/QPVHii/M2tMYgwup3MErfr4jPu/Y3CYpoxvSln6oG0A80iMz2/wLj1WaCNPHSPF0N7A04pJLStJ6osWMYinBLk=}
bot:
  automerge: true
